<?php

namespace App\Controller;


use App\Model\Entity\Department;

class  StudentController extends AppController {

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Department');
    }

    public  function index()
    {
        $show = $this->paginate($this->Student);
        $this->set(compact('show'));
    }

    public function view($sid = null){

        $view = $this->Student->get($sid,[
            'contain' => ['Department']
        ]);

        $this->set(compact('view'));
    }

    public function add(){


        $course = $this->Department->find('all')->all();
        $insert = $this->Student->newEmptyEntity();

        if($this->request->is('post')){
            $insert = $this->Student->patchEntity($insert,$this->request->getData());

            if($this->Student->save($insert)){
                $this->Flash->success('Data Inserted Successfully');

                return $this->redirect(['action'=>'index']);
            }
            $this->Flash->error('Error Something Went Wrong');
        }

        $this->set(compact('course'));
    }
    public function edit($id = null){

        $edit = $this->Student->get($id,[
            'contain' => ['Department']
        ]);

        $course = $this->Department->find('all')->all();
        if($this->request->is(['patch','put','post'])){
            $edit = $this->Student->patchEntity($edit,$this->request->getData());

            if($this->Student->save($edit)){
                $this->Flash->success('Record Updated Successfully');

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error('Error Accrued When Updating A record ');
        }
            $this->set(compact('edit', 'course'));
    }

    public function delete($id=null){
        $delete = $this->Student->get($id);

        if($this->Student->delete($delete)){
            $this->Flash->success("Record Deleted Successfully");
        }
        else{
            $this->Flash->error("Something Went Wrong..");
        }
        return $this->redirect(["action" => 'index']);
    }
}
