<?php

namespace  App\Controller;
use Cake\Routing\Router;

class ThemeController extends AppController{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('ThemeLayout');
    }
    public function index(){

    }
}


