<?php

namespace  App\Model\Table;
use  Cake\ORM\Table;
use Cake\Validation\Validator;


class  DepartmentTable extends Table{

    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->setTable('department');
        $this->setDisplayField('name');
        $this->setPrimaryKey('cid');

        $this->hasMany('Student',[
            'foreignKey' => 'course',
        ]);
    }
}
