<?php

namespace  App\Model\Table;
use Cake\ORM\Table;
use Cake\Validation\Validator;


class StudentTable extends Table{

    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub


        $this->setTable('student');
        $this->setPrimaryKey('sid');
        $this->setDisplayField('name');

        $this->belongsTo('Department',[
           'foreignKey'=> 'course'
        ]);
    }

    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->scalar('name')
            ->notEmptyString('name');
//            ->maxLength('name', 50);
        $validator
            ->scalar('address')
            ->notEmptyString('address');
//            ->maxLength('address', 50);
        $validator
            ->scalar('course')
            ->notEmptyString('course');
        return  $validator;
    }
}
